class WebLocator:
    """
        This class is used to contain all the locator that are required to perform the testing for the checkout page
    """
    def __init__(self):
        self.add_to_cart_image="//button[@class='btn btn-inverse btn-block btn-lg dropdown-toggle']"
        self.checkout_button_locator="//strong[normalize-space()='Checkout']"
        self.radio_button_locator="//input[@value='guest']"
        self.continue_locator="//input[@id='button-account']"
        self.first_name_locator="//input[@id='input-payment-firstname']"
        self.last_name_locator="//input[@id='input-payment-lastname']"
        self.mail_locator="//input[@id='input-payment-email']"
        self.phone_no_locator="//input[@id='input-payment-telephone']"
        self.address_locator="//input[@id='input-payment-address-1']"
        self.city_locator="//input[@id='input-payment-city']"
        self.post_code_locator="//input[@id='input-payment-postcode']"
        self.continue_input_locator="//input[@id='button-guest']"
        self.state_locator="//select[@id='input-payment-zone']"
        self.continue2_locator="//input[@id='button-shipping-method']"
        self.terms_condition_locator="//input[@name='agree']"
        self.continue3_locator="//input[@id='button-payment-method']"
        self.final_price_locator="//td[normalize-space()='$130.00']"
        self.confirm_locator="//input[@id='button-confirm']"
        self.success_message_locator="//h1[normalize-space()='Your order has been placed!']"